// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, name, url, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, name, url, user_id
`

type CreateFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const getFeedsAndUser = `-- name: GetFeedsAndUser :many
SELECT feeds.id, feeds.created_at, feeds.updated_at, feeds.name, url, user_id, users.id, users.created_at, users.updated_at, users.name FROM feeds JOIN users ON feeds.user_id = users.id
`

type GetFeedsAndUserRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Url         string
	UserID      uuid.UUID
	ID_2        uuid.UUID
	CreatedAt_2 time.Time
	UpdatedAt_2 time.Time
	Name_2      string
}

func (q *Queries) GetFeedsAndUser(ctx context.Context) ([]GetFeedsAndUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsAndUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsAndUserRow
	for rows.Next() {
		var i GetFeedsAndUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.ID_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.Name_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsFromURL = `-- name: GetFeedsFromURL :one




SELECT id, created_at, updated_at, name, url, user_id FROM feeds WHERE url = $1
`

// -- name: GetFeeds :many
// SELECT * FROM feeds JOIN users ON feeds.user_id = users.id;
// -- name: GetFeedsFromUser :many
// SELECT * FROM feeds WHERE user_id = $1;
// -- name: GetUserFromFeed :one
// SELECT * FROM feeds JOIN users ON feeds.user_id = users.id WHERE feeds.id = $1;
// -- name: GetUserNameFromFeedID
// -- name: DeleteUsers :exec
// DELETE FROM users;
// -- name: GetUsers :many
// SELECT * FROM users;
func (q *Queries) GetFeedsFromURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedsFromURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
